import type { Indicator } from "./types.ts";

const exit = { stopAtrMult: 1.4, atrLength: 14, targetR: 2 };

export const seeds: Indicator[] = [
  {
    id: "seed-pullback",
    name: "回踩金线",
    thesis: "15 分钟上升结构里，价格踩到 21 均线又收回，且 RSI 还没热。",
    sourceNote: "哨所自建。趋势看 21/55，回踩看当根最低与收盘。",
    source: "seed",
    side: "long",
    timeframe: "15m",
    armed: true,
    logic: "all",
    conditions: [
      { id: "p1", label: "趋势在上", left: { type: "ema", length: 21 }, op: "gt", right: { type: "ema", length: 55 } },
      { id: "p2", label: "踩到金线", left: { type: "low" }, op: "lte", right: { type: "ema", length: 21 } },
      { id: "p3", label: "收回金线", left: { type: "close" }, op: "gt", right: { type: "ema", length: 21 } },
      { id: "p4", label: "尚未过热", left: { type: "rsi", length: 14 }, op: "lte", right: { type: "const", value: 65 } },
    ],
    exit,
    updatedAt: 0,
  },
  {
    id: "seed-breakout",
    name: "前高突破",
    thesis: "5 分钟收盘上穿近 20 根前高，并且还站在 55 均线之上。",
    sourceNote: "哨所自建。前高不含当根，避免把这根本身算进区间。",
    source: "seed",
    side: "long",
    timeframe: "5m",
    armed: true,
    logic: "all",
    conditions: [
      { id: "b1", label: "收盘破前高", left: { type: "close" }, op: "cross_up", right: { type: "highest", length: 20 } },
      { id: "b2", label: "站上慢线", left: { type: "close" }, op: "gt", right: { type: "ema", length: 55 } },
      { id: "b3", label: "三根有速度", left: { type: "roc", length: 3 }, op: "gt", right: { type: "const", value: 0.05 } },
    ],
    exit: { stopAtrMult: 1.2, atrLength: 14, targetR: 1.8 },
    updatedAt: 0,
  },
  {
    id: "seed-fade",
    name: "超买回落",
    thesis: "RSI 跌回 70 下方，收盘落到 21 均线下，MACD 柱为负。默认不武装。",
    sourceNote: "哨所自建空头模板。",
    source: "seed",
    side: "short",
    timeframe: "15m",
    armed: false,
    logic: "all",
    conditions: [
      { id: "f1", label: "离开超买", left: { type: "rsi", length: 14 }, op: "cross_down", right: { type: "const", value: 70 } },
      { id: "f2", label: "落到均线下", left: { type: "close" }, op: "lt", right: { type: "ema", length: 21 } },
      { id: "f3", label: "柱在零下", left: { type: "macd_hist" }, op: "lt", right: { type: "const", value: 0 } },
    ],
    exit: { stopAtrMult: 1.3, atrLength: 14, targetR: 2 },
    updatedAt: 0,
  },
  {
    id: "seed-community-long",
    name: "社区黄金合流",
    thesis: "公开 Pine 原意是 RSI 上穿 30、MACD 金叉、价在 MA9 上、又碰到布林下轨，四件事同一根几乎不响。改成超卖区、柱为正、价在均线上、布林偏下。",
    sourceNote: "UsamaChoudhry/xauusd-tradingview-indicator · gold_indicator.pine",
    source: "github",
    sourceUrl: "https://github.com/UsamaChoudhry/xauusd-tradingview-indicator",
    side: "long",
    timeframe: "15m",
    armed: true,
    logic: "all",
    conditions: [
      { id: "g1", label: "RSI 偏低", left: { type: "rsi", length: 14 }, op: "lte", right: { type: "const", value: 42 } },
      { id: "g2", label: "MACD 柱为正", left: { type: "macd_hist" }, op: "gt", right: { type: "const", value: 0 } },
      { id: "g3", label: "价在 MA9 上", left: { type: "close" }, op: "gt", right: { type: "sma", length: 9 } },
      { id: "g4", label: "布林偏下", left: { type: "bb_pct", length: 20 }, op: "lte", right: { type: "const", value: 0.4 } },
    ],
    exit: { stopAtrMult: 1.5, atrLength: 14, targetR: 2 },
    updatedAt: 0,
  },
  {
    id: "seed-laomao-long",
    name: "老猫突破多",
    thesis: "价格行为：收盘站上 SMA9，并且放量收破前 8 根高点。入场后按 1、2、3 倍风险挂三档止盈。",
    sourceNote: "按老猫那张图的结构写的。SMA9 两侧力量、放量突破、三档止盈。不是原版源码。",
    source: "tradingview",
    side: "long",
    timeframe: "5m",
    armed: true,
    logic: "all",
    conditions: [
      { id: "c1", label: "站上 SMA9", left: { type: "close" }, op: "gt", right: { type: "sma", length: 9 } },
      { id: "c2", label: "收盘破前高", left: { type: "close" }, op: "cross_up", right: { type: "highest", length: 8 } },
      { id: "c3", label: "三根有速度", left: { type: "roc", length: 3 }, op: "gt", right: { type: "const", value: 0.04 } },
    ],
    exit: { stopAtrMult: 1.15, atrLength: 14, targetR: 2 },
    updatedAt: 0,
  },
  {
    id: "seed-laomao-short",
    name: "老猫突破空",
    thesis: "收盘落到 SMA9 下，并且放量收破前 8 根低点。止损放在突破那根外侧，止盈分三档。",
    sourceNote: "和突破多对称。图上的买卖表用 SMA9 离价的远近来拆百分比。",
    source: "tradingview",
    side: "short",
    timeframe: "5m",
    armed: true,
    logic: "all",
    conditions: [
      { id: "d1", label: "落到 SMA9 下", left: { type: "close" }, op: "lt", right: { type: "sma", length: 9 } },
      { id: "d2", label: "收盘破前低", left: { type: "close" }, op: "cross_down", right: { type: "lowest", length: 8 } },
      { id: "d3", label: "三根有速度", left: { type: "roc", length: 3 }, op: "lt", right: { type: "const", value: -0.04 } },
    ],
    exit: { stopAtrMult: 1.15, atrLength: 14, targetR: 2 },
    updatedAt: 0,
  },
];
